ALTER TABLE properties ADD COLUMN IF NOT EXISTS contact_phone TEXT NOT NULL DEFAULT '';
ALTER TABLE properties ADD COLUMN IF NOT EXISTS contact_email TEXT NOT NULL DEFAULT '';
ALTER TABLE properties ADD COLUMN IF NOT EXISTS upi_id TEXT NOT NULL DEFAULT 'hotelos@upi';
ALTER TABLE properties ADD COLUMN IF NOT EXISTS upi_name TEXT NOT NULL DEFAULT 'HotelOS';
ALTER TABLE properties ADD COLUMN IF NOT EXISTS check_in_time TEXT NOT NULL DEFAULT '14:00';
ALTER TABLE properties ADD COLUMN IF NOT EXISTS check_out_time TEXT NOT NULL DEFAULT '11:00';
ALTER TABLE properties ADD COLUMN IF NOT EXISTS logo_url TEXT NOT NULL DEFAULT '';
